.checks_job_template:
  image: golang:1.25
  tags:
    - public-docker
  variables:
    GOCACHE: "$CI_PROJECT_DIR/.cache/go-build"
    GOMODCACHE: "$CI_PROJECT_DIR/.cache/go-mod"
  cache:
    key: "go-$CI_COMMIT_REF_SLUG"
    paths:
      - .cache/go-build/
      - .cache/go-mod/
  before_script:
    - mkdir -p "$GOCACHE" "$GOMODCACHE"
    - go version
  rules:
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_PIPELINE_SOURCE == "push"'
    - when: never

stages:
  - test
  - coverage
  - build

test:
  extends: .checks_job_template
  stage: test
  script:
    - make test

coverage:
  extends: .checks_job_template
  stage: coverage
  script:
    - make coverage
  coverage: '/Overall coverage:\s+(\d+(?:\.\d+)?%)/'
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - coverage.out
      - coverage.html

build:
  extends: .checks_job_template
  stage: build
  script:
    - make build
  artifacts:
    name: "jbs-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"
    expire_in: 1 week
    paths:
      - jbs
