package run

import (
	"fmt"
	"maps"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
)

var shellName = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

type runScriptSpec struct {
	RunDir    string
	WorkDir   string
	SourceDir string
	StepName  string
	Work      ManifestWork
	Body      string
	NoStrict  bool
}

func renderRunScript(spec runScriptSpec) (string, error) {
	paths := map[string]string{
		"JBS_RUN_DIR":  filepath.Clean(spec.RunDir),
		"JBS_SRC_DIR":  filepath.Clean(spec.SourceDir),
		"JBS_WORK_DIR": filepath.Clean(spec.WorkDir),
	}
	for name, path := range paths {
		if !filepath.IsAbs(path) {
			return "", fmt.Errorf("%s must be absolute, got %q", name, path)
		}
	}
	values := map[string]string{
		"JBS_RUN_DIR":  paths["JBS_RUN_DIR"],
		"JBS_SRC_DIR":  paths["JBS_SRC_DIR"],
		"JBS_STEP":     spec.StepName,
		"JBS_ROW":      rowDir(spec.Work.Row),
		"JBS_WORK_DIR": paths["JBS_WORK_DIR"],
	}

	var b strings.Builder
	b.WriteString("#!/usr/bin/env bash\n")
	b.WriteString("# generated by jbs\n")
	if !spec.NoStrict {
		b.WriteString("set -euo pipefail\n")
	}
	b.WriteString("\n")
	for _, name := range slices.Sorted(maps.Keys(values)) {
		fmt.Fprintf(&b, "export %s=%s\n", name, bashQuote(values[name]))
	}
	b.WriteString("\n")
	for _, name := range slices.Sorted(maps.Keys(spec.Work.Values)) {
		fmt.Fprintf(&b, "export %s=%s\n", name, bashQuote(spec.Work.Values[name]))
	}
	b.WriteString("\n")
	b.WriteString(strings.TrimRight(spec.Body, "\n"))
	b.WriteString("\n")
	return b.String(), nil
}

func bashQuote(s string) string {
	if s == "" {
		return "''"
	}
	return "'" + strings.ReplaceAll(s, "'", "'\"'\"'") + "'"
}
