package run

import (
	"fmt"
	"maps"
	"regexp"
	"slices"
	"strings"
)

var shellName = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

func renderRunScript(runDir, stepName string, work ManifestWork, step ManifestStep, body string) string {
	workDir := filepathForWork(runDir, step, work)
	values := map[string]string{
		"JBS_RUN_DIR":  runDir,
		"JBS_STEP":     stepName,
		"JBS_ROW":      rowDir(work.Row),
		"JBS_WORK_DIR": workDir,
	}

	var b strings.Builder
	b.WriteString("#!/usr/bin/env bash\n")
	b.WriteString("# generated by jbs\n\n")
	for _, name := range slices.Sorted(maps.Keys(values)) {
		fmt.Fprintf(&b, "export %s=%s\n", name, bashQuote(values[name]))
	}
	b.WriteString("\n")
	for _, name := range slices.Sorted(maps.Keys(work.Values)) {
		fmt.Fprintf(&b, "%s=%s\n", name, bashQuote(work.Values[name]))
	}
	b.WriteString("\n")
	b.WriteString(strings.TrimRight(body, "\n"))
	b.WriteString("\n")
	return b.String()
}

func bashQuote(s string) string {
	if s == "" {
		return "''"
	}
	return "'" + strings.ReplaceAll(s, "'", "'\"'\"'") + "'"
}
